### ISSUE TITLE
What exactly is this?

### ISSUE THREAD

**Issue by Drakaroft** [MattRix/UnityDecompiled#3]
I don't understand what is this, compiling the solution i will get a compiled build of entire Unity? (editor+engine?). Or just two dll?

**Comment by MattRix** [comment]
You aren't meant to compile it.

The code has been created by decompiling Unity's built-in dll files. I put
it in a solution just to make it easier to browse the files.

**Comment by Drakaroft** [comment]
Aaahhhh right, thanks!
