### ISSUE TITLE
This seems to be practically useless.

### ISSUE THREAD

**Issue by erherhh4herh** [MattRix/UnityDecompiled#4]
This just seems to be methods that are called and executed elsewhere. I have found no actual computational code within any of the scripts I have searched. For example, the collider script:

https://github.com/MattRix/UnityDecompiled/blob/master/UnityEngine/UnityEngine/Collider.cs

Nothing in there seems to actually compute the way colliders react. I would appreciate it if you could add the computational source code so that we can decompile/modify the internal base code with custom methods, variables etc. 

Please and thank you,
erherhh4herh :)

**Comment by MattRix** [comment]
It doesn't have decompiled native code, only the C# code. It's not useless, it's very handy when trying to figure out how certain things in the editor work, especially when making custom editor tools. And even if it had the native code, you wouldn't be able to recompile it anyway. 

For physics stuff specifically, Unity uses PhysX under the hood, so you can [look at the PhysX source code](https://developer.nvidia.com/physx-source-github) to learn more about how that works.

**Comment by dylan-hart** [comment]
This is often the first place I go when I'm extending the editor. I've found it useful for many other things as well. Thanks!
