### ISSUE TITLE
List of types per namespace?

### ISSUE THREAD

**Issue by Geri-Borbas** [MattRix/UnityDecompiled#6]
Hi,

is there a chance to get a list of type names (classes, delegates, enums, interfaces, structs) per namespaces during decompilation?

I'm thinking of creating a gammar / color theme for VS Code, so Unity class colors could be downtoned. This could be an input for that.

**Comment by MattRix** [comment]
Interesting idea! I don't decompilation is the place to do that, instead you could generate that list using reflection at runtime. For example: http://stackoverflow.com/a/1315668

**Comment by Geri-Borbas** [comment]
Yay, thanks for getting back!
I'm a great admirer of your work since Trainyard.

Me also was looking into runtime inspection since than. With [Edge.js](http://tjanczuk.github.io/edge) I could lookup / **inspect Unity on client side** packed directly into a VS Code extension. Would be no any list to maintain then. Also, it could inspect **project assemblies as well**, so I could color static / instance methods differently, and more.

**Comment by Geri-Borbas** [comment]
Well, in the end I used the `.csproj` files actually from this repo. 😄 
A good approximation at least.

In case you're interested in VS Code., may take a look at: https://twitter.com/_eppz/status/849450641760161792

**Comment by MattRix** [comment]
Great that you got this worked out!

**Comment by Geri-Borbas** [comment]
Thanks for this repo again!

Since than I used it for this writeup as well - http://eppz.eu/blog/unity-editor-icon-assets/, https://twitter.com/_eppz/status/855432605189234688 - to locate Editor Assets / Textures / Icons. 

Endless source of Unity wisdom. 😄

**Comment by MattRix** [comment]
Oh nice! What's funny is that a few months ago, I actually dumped out the icons as well. I wanted to use them when making editor tools. I generated a simple webpage with all of them in it. I only use it for my own stuff, I don't think I ever put it up online anywhere.

**Comment by Geri-Borbas** [comment]
I thought the same, to use those icons when shipping Editor tools.

In the end, I made a class - https://github.com/eppz/Unity.Library.eppz/blob/master/EditorUtils/SliceRenamer.cs#L30 - that creates a Texture2D from a Base64 strings - https://github.com/eppz/Unity.Library.eppz/blob/master/EditorUtils/SliceRenamer.cs#L273 -, so the textures are in the Editor Tool source code as well.

Sorry for keep bothering you, I'm just enjoying conversation with such Legend. 😄

**Comment by MattRix** [comment]
Ah, great idea to store the icons as Base64! It's always a pain to have to include extra files, so I really like that approach :)

**Comment by Geri-Borbas** [comment]
Yap, one can ship / maintain an Editor Tool in a single `.cs` source.
