### ISSUE TITLE
Add source for UnityEngine.Networking

### ISSUE THREAD

**Issue by apkd** [MattRix/UnityDecompiled#8]
Available here: https://bitbucket.org/Unity-Technologies/networking

This is especially useful since `UnityEngine.Networking.NetworkManager` is an inheritable class with many virtual methods.

**Comment by MattRix** [comment]
Hmm so are you talking about just including a link to that repo in the readme? (which is what I do with the UI) Or are you talking about taking the source code from that repo and putting it in this repo?

**Comment by apkd** [comment]
That's depending on what you want this repo to be - just a very slight suggestion on my part. I initially thought that you included the whole UI respository.

If you don't want to include the whole repo, a link will be just fine. I ended up posting here because I searched this repo for the source of `NetworkManager.cs` and didn't find it - at the time didn't even realize that it was open source.

**Comment by MattRix** [comment]
Yep, this makes sense. I'm thinking that maybe I will include the decompiled source of it here, but also include a link to the open-source code as well... that way when people search for it here, they will find it, but it will also limit the potential complication of bringing in code from multiple sources.
