### ISSUE TITLE
Source for the UnityEditor.Graphs namespace is unavailible

### ISSUE THREAD

**Issue by Hadien** [MattRix/UnityDecompiled#9]
I was looking around for the code that shows how the Animator EditorWindow is drawn and it appears the Editor Code for that resides in this namespace. I simply selected a state and Debug.Logged the Editor class that draws the AnimatorState to the inspector, which was found to be drawn by UnityEditor.Graphs.AnimationStateMachine.StateEditor. looking through the GitHub I wasn't able to find anything relating to this.

was the source simply skipped over, unavailable, or do you not have permission to show this specific namespace?

**Comment by MattRix** [comment]
I think it was probably just skipped over, I'll try to include it next time I do a decompilation.
